name: Encrypt edge.js on Change

on:
 workflow_dispatch: # 手动触发
  push:
    branches:
      - main  # 根据你的主分支名称调整
    paths:
      - '明文源码.js'  # 替换为文件的实际路径

jobs:
  encrypt-edge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Encrypt edge.js
        run: |
          openssl aes-256-cbc -in 明文源码.js -out edge.enc -pass pass:${{ secrets.ENCRYPTION_KEY }}
        # 注意：加密后的文件为 edge.enc，建议将 .enc 文件添加到 .gitignore

      - name: Commit and push encrypted file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add edge.enc
          git commit -m "Auto-encrypt edge.js [skip ci]"  # 使用 [skip ci] 避免循环触发
          git push origin main
