- name: Download & Encrypt
  if: steps.check_diff.outputs.DIFF == 'true'
  env:
    ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
  run: |
    # 下载源文件（保持原始文件名）
    curl -s "https://raw.githubusercontent.com/xrw002/edgetunnel/main/_worker.js" -o _temp.js
    
    # 使用双引号包裹seed参数（关键修复）
    javascript-obfuscator _temp.js \
      --compact true \
      --controlFlowFlattening true \
      --stringArrayEncoding rc4 \
      --stringArrayThreshold 1 \
      --rotateStringArray true \
      --splitStrings true \
      --identifierNamesGenerator hexadecimal \
      --identifiersPrefix 'edge_' \
      --renameGlobals true \
      --transformObjectKeys true \
      --seed "${{ secrets.ENCRYPT_KEY }}" \  # 添加双引号
      -o src/edge-prod.js
    
    # 保存commit记录（使用校验码防篡改）
    echo "${{ steps.get_commit.outputs.latest_commit }}" > last_commit.txt
    md5sum src/edge-prod.js | cut -d ' ' -f1 >> last_commit.txt
